In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
path='/content/drive/MyDrive/ai_project/adults-media-literacy-2025-respondent-level-data.csv'

In [5]:
print(path)

/content/drive/MyDrive/ai_project/adults-media-literacy-2025-respondent-level-data.csv

In [13]:
import pandas as pd #引入pandas命名为pd
df=pd.read_csv(path) #读取csv

/tmp/ipykernel_1277/2229550512.py:2: DtypeWarning: Columns (92,93,94,95,96,97,98,99,100,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,135,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,224,225,226,227,229,230,231,232) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv(path)

In [14]:
df.shape #line, column

(7533, 566)

In [20]:
df.head()#读取表格前五行

,ZID_AUTO,P_METHOD,MODULEA,MODULEB,MODULEC,MODULED,ONLINECAPI_GROUPS,S5,REGION1,URBAN,...,E8H,E8I,E8J,E8K,E8L,E8M,E8N,E9,FVUL,WT
0,{7B4ACFBE-CF64-29F6-4CE6-594F02C48193},3,0,1,0,1,4,1,6,1,...,0,0,0,1,0,0,0,1,1,0.6544
1,{DB4953B5-6593-9153-B23F-B18967A5E9BD},3,1,1,0,0,1,1,6,1,...,0,0,1,0,0,0,1,8,,0.9602
2,{6A4D0DB9-EBBD-E64D-BA65-614756DF138E},3,1,0,1,0,3,1,6,1,...,0,0,0,1,0,0,0,2,2,1.0837
3,{2D4293AD-95FE-11CC-DB42-86DF038FF8A3},3,0,1,0,1,4,1,6,1,...,0,1,0,0,0,0,1,8,,1.0826
4,{BB4A5C6F-0BCB-50DE-AFC4-5E87338E4DB2},3,1,0,0,1,5,1,6,1,...,0,0,0,1,0,0,0,8,,1.1349

In [22]:
df['A6'].value_counts()#一列=Series，DataFrame = 很多个 Series并排组成的整张表。
                       #.value_counts()--数一数这一列里，每个值各出现了多少次, Excel 里对每个答案分别写 =COUNTIF(LC:LC, 1)、=COUNTIF(LC:LC, 2)
                       #4018，是空格，没有被问到A6的（不是没有）
                       #同一列里的数据，必须是同一种类型，回答3，2其实是文字，因为有空格和数字在不属于同一类，

A6
     4018
3    1156
2     893
1     604
4     525
5     337
Name: count, dtype: int64

In [32]:
df=pd.read_csv(path, na_values=' ')#na_values--缺失值，=后面什么是缺失值--''空格

In [33]:
df['A6'].value_counts()#空格现在是NaN，not a number为小数，所以123，也变成小数

A6
3.0    1156
2.0     893
1.0     604
4.0     525
5.0     337
Name: count, dtype: int64

In [35]:
df['A6'].value_counts().sum()#是数字就加起来=有效样本

np.int64(3515)

In [36]:
df['A6'].isna().sum()#对每行检查"这一格是不是缺失值"，是就记为 True，不是就记为 False
                     #把 True 当成 1、False 当成 0，加起来，就是缺失值的个数

np.int64(4018)

In [37]:
df['MODULEA']==1#==就是等于（1吗）
                #data type：bool布尔值，回答true/flase

0       False
1        True
2        True
3       False
4        True
        ...
7528    False
7529    False
7530    False
7531    False
7532     True
Name: MODULEA, Length: 7533, dtype: bool

In [41]:
sample=df[(df['MODULEA']==1)&(df['INTUSED']==1)]#相当于excel =COUNTIFS(A:A,1,B:B,1)
                                                #()布尔值
                                                #& 同时满足
                                                #df[（）&（）]只留下True值

In [42]:
sample.shape

(3515, 566)

In [44]:
sample.head()

,ZID_AUTO,P_METHOD,MODULEA,MODULEB,MODULEC,MODULED,ONLINECAPI_GROUPS,S5,REGION1,URBAN,...,E8H,E8I,E8J,E8K,E8L,E8M,E8N,E9,FVUL,WT
1,{DB4953B5-6593-9153-B23F-B18967A5E9BD},3,1,1,0,0,1,1,6,1,...,0,0,1,0,0,0,1,8,NaN,0.9602
7,{FE4198E9-DD4F-8078-51C7-CE5A9F37C6A1},3,1,1,0,0,1,1,6,1,...,0,0,0,1,0,0,0,2,2.0,0.9602
9,{374941F6-C237-3BCA-2848-AEF0666628A9},3,1,0,0,1,5,1,6,1,...,0,0,0,1,0,0,0,1,1.0,1.3057
13,{BF4DD4AB-D01A-2E1A-437E-F43851E2CE8A},3,1,0,0,1,5,1,7,1,...,0,0,0,0,0,1,0,8,NaN,1.1078
15,{B5476936-AD2D-7BF6-3788-CB89EF5CA2AD},3,1,1,0,0,1,1,7,1,...,0,0,0,1,0,0,0,8,NaN,1.3081

In [45]:
sample['A6'].isna().sum()

np.int64(0)

## Python 入门②：交叉表

In [49]:
pd.crosstab(sample['P_METHOD'],sample['A6'], normalize='index').round(3)#crossstab()交叉表功能,
                                                                        #normalize='index'--parameter参数，附加功能
                                                                        #normalize--按比例格式，index--行，每个数/行总和
                                                                        #round()3--保留3位小数

A6          1.0    2.0    3.0    4.0    5.0
P_METHOD
2         0.193  0.278  0.337  0.119  0.073
3         0.097  0.170  0.300  0.256  0.177

In [51]:
tab=pd.crosstab(sample['P_METHOD'],sample['A6'], normalize='index')#存进tab
tab #显示给我看 意思

A6             1.0       2.0       3.0       4.0       5.0
P_METHOD
2         0.193477  0.278124  0.337120  0.118725  0.072554
3         0.096692  0.170483  0.300254  0.255725  0.176845

In [52]:
(tab[4.0]+tab[5.0]).round(3)#取列series，pandas会按index行配对相加，4.0--数字不用''

P_METHOD
2    0.191
3    0.433
dtype: float64

In [62]:
(tab[1.0]+tab[2.0]).round(3)

P_METHOD
2    0.472
3    0.267
dtype: float64

In [59]:
pd.crosstab(sample['SUMAI'],sample['A6'],normalize='index')

A6          1.0       2.0       3.0       4.0       5.0
SUMAI
1.0    0.262621  0.336408  0.305340  0.071845  0.023786
2.0    0.043657  0.139209  0.386326  0.256178  0.174629
3.0    0.041494  0.128631  0.240664  0.273859  0.315353

In [60]:
tab2=pd.crosstab(sample['SUMAI'],sample['A6'],normalize='index')

In [74]:
(tab2[1.0]+tab2[2.0]+tab2[3.0]).round(3)

SUMAI
1.0    0.904
2.0    0.569
3.0    0.411
dtype: float64

In [77]:
result=(tab2[1.0]+tab2[2.0]+tab2[3.0]).round(3)

In [78]:
result.loc[3.0]#location 取行

np.float64(0.411)

In [80]:
tab3=pd.crosstab(sample['E9']==8,sample['A6'],normalize='index')
tab3

A6          1.0       2.0       3.0       4.0       5.0
E9
False  0.181492  0.275108  0.331779  0.134146  0.077475
True   0.134801  0.173315  0.317744  0.207703  0.166437

In [83]:
(tab3[4.0]+tab3[5.0]).round(3)

E9
False    0.212
True     0.374
dtype: float64

In [84]:
result1=(tab3[4.0]+tab3[5.0]).round(3)

In [91]:
result1.loc[True]#true不是数字也不是文字，不用''

np.float64(0.374)